name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  main:
    name: Push to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@main
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
